// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jiezjfwsbemcmtbsoifi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImppZXpqZndzYmVtY210YnNvaWZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMzQ5MjksImV4cCI6MjA2NTkxMDkyOX0.MlvpyjPasQ6i3PRHOBT3uc5mQu8WtKgLOVsTvJv6-nM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);